require("plugins.rose-pine")
require("plugins.snacks")
require("plugins.which-key")
require("plugins.noice")

require("plugins.tree-sitter")
require("plugins.nvim-treesitter-textobjects")
require("plugins.ts-comments")
require("plugins.nvim-ts-autotag")
require("plugins.mini-ai")

require("plugins.nvim-autopairs")
require("plugins.flash")
require("plugins.yanky")
require("plugins.grug-far")
require("plugins.vim-tmux-navigator")
require("plugins.oil")
require("plugins.harpoon")

require("plugins.inlay-hint-trim")
require("plugins.tiny-inline-diagnostics")
require("plugins.blink")
require("plugins.lsp")
require("plugins.conform")
require("plugins.nvim-lint")
require("plugins.trouble")
require("plugins.todo-comments")
require("plugins.markdown-preview")
require("plugins.render-markdown")
require("plugins.sidekick")
require("plugins.neocursor")

require("plugins.venv-selector")
require("plugins.nvim-dap")
require("plugins.neotest")
require("plugins.diffview")
require("plugins.gitsigns")
require("plugins.project")
require("plugins.bufferline")
require("plugins.lualine")

require("plugins.auto-session")
